### ISSUE TITLE
Multiple language filter for selecting more than one language at a time

### ISSUE THREAD

**Issue by sahitya-chandra** [The-Enthusiast-404/git-begin#35] opened 2024-08-24 17:45 UTC
Currently, we can only choose single language. So update this feature with which we can select more than on language at a time.

**Comment by dotslashbit** [comment] 2024-08-24 18:01
Assigning this to you

**Comment by sahitya-chandra** [comment] 2024-08-25 05:18
@dotslashbit can you explain me a little bit file structure of this project. I am find some difficulty in understanding this.

**Comment by dotslashbit** [comment] 2024-08-25 09:28
Sure:
Its a standard Remix project where we have all the code inside the app directory. Its using tailwindCSS and shadcn for styling.

Inside the app directory, we have components directory (this is where we store all the components)
Inside the app/routes directory we have index.tsx file (this is what will render on the page if you'll go to the homepage). 

There's a services directory inside app directory, this has two files github.ts and gitlab.ts, both of these files are interacting with github and gitlab API 

The types directory consists of all the types we are using, if you know how to use react + typescript then this is a standard way to work with types

Let me know if you need any help

**Comment by sahitya-chandra** [comment] 2024-08-25 18:10
@dotslashbit i have converted the language in accordion with multiple lang. option but for some reason language state is not updating
#
![Screenshot from 2024-08-25 23-32-43](https://github.com/user-attachments/assets/4d00ff44-cd09-4ded-8373-0dd819ba3bc1)
![Screenshot from 2024-08-25 23-35-11](https://github.com/user-attachments/assets/3e90a410-1c84-4a48-a5a5-906631b4a2e4)

**Comment by sahitya-chandra** [comment] 2024-08-25 18:11
can u help...

**Comment by dotslashbit** [comment] 2024-08-25 18:13
@sahitya-chandra I can look it up tomorrow, hope that's fine 

Just do one thing, open up a PR with the description of closes #<issue>

Please keep a space between closes and #

By opening a PR I can review it and let you know

**Comment by sahitya-chandra** [comment] 2024-08-25 18:26
@dotslashbit done

**Comment by dotslashbit** [comment] 2024-08-25 18:28
Thanks, I'll look into it tomorrow morning

**Comment by pamarthiabhinav** [comment] 2024-08-25 19:25
@sahitya-chandra out of curiosity. I have few questions.

- Did you update the language to hold multiple values like an arra while declaring the useState for it in the (_index.tsx)[https://github.com/The-Enthusiast-404/git-begin/blob/main/app/routes/_index.tsx] file?
Something like this:
  ```javascript
    const [languages, setLanguages] = useState([]);
  ```
- did you create a function, which takes the language data and filter out the unselected options from available languages and then use setLanguage? like this:
  ```javascript
    const handleLanguageChange = (value) => {
      if (languages.includes(value)) {
        // if the value is already in the state, the unselect it
        setLanguages(languages.filter((language) => language !== value));
      }
      else {
        // else add it to the state
        setLanguages([...languages, value]);
      }
    }
  ```

@dotslashbit Correct me if I went wrong?

**Comment by dotslashbit** [comment] 2024-08-25 19:28
@pamarthiabhinav this is the way to go.

@pamarthiabhinav It will be great if you want to  review and help him out.

I'll always review, that's for sure but if you wanna get involved then feel free to do so

**Comment by sahitya-chandra** [comment] 2024-08-25 19:29
@pamarthiabhinav  i created state but i created it in wrong file but now i have fixed it

**Comment by sahitya-chandra** [comment] 2024-08-25 19:31
@pamarthiabhinav thanks for telling the correct file i was stuck at for some time

**Comment by pamarthiabhinav** [comment] 2024-08-25 19:31
@sahitya-chandra great buddy. Now go for the next steps and start you contributions 🙌

**Comment by pamarthiabhinav** [comment] 2024-08-25 19:36
FYI @sahitya-chandra changing the language selection is just not the task here I think so, but you need to make sure how that can be used in the API calls in the [github.ts](https://github.com/The-Enthusiast-404/git-begin/blob/1eedd9fd4c29a6c0081ce0222692c27d1a988ee3/app/services/github.ts) and [gitlab.ts](https://github.com/The-Enthusiast-404/git-begin/blob/1eedd9fd4c29a6c0081ce0222692c27d1a988ee3/app/services/gitlab.ts) files, Which actually uses the change to retrieve the issues

Ping here if you stuck anywhere, either me or @dotslashbit can help or assist you!

Good Luck @dotslashbit ✌️

**Comment by dotslashbit** [comment] 2024-08-25 19:40
@pamarthiabhinav Yeah, that's what I wrote in the PR as a comment. I asked him to go step by step, so lets first get the UI working by implementing multi checks and then we can fix the github/gitlab api query to get it to fully functional feature.

@sahitya-chandra Remember, there's no rush, and if there's any help you need or if you are stuck, just ping me or @pamarthiabhinav 

You are doing great 👍🏻

**Comment by sahitya-chandra** [comment] 2024-08-25 19:43
@pamarthiabhinav @dotslashbit Thanks a lot u both for guiding me . Actually i have recently started contributing and completed web dev last month so their are many i am unawair of.
and yaah i will ping you when i am stuck some where.

**Comment by dotslashbit** [comment] 2024-08-27 13:12
@ST-KO will work on it

**Comment by sahitya-chandra** [comment] 2024-08-27 15:56
@dotslashbit sorry i am unable to fix this...

**Comment by dotslashbit** [comment] 2024-08-27 15:57
@sahitya-chandra no worries even I can't solve a good amount of issues, it's pretty normal

**Comment by dotslashbit** [comment] 2024-08-27 15:58
@sahitya-chandra let me know if you want to solve any issues, I'll tag you if a new issue comes up

**Comment by ST-KO** [comment] 2024-08-29 02:03
@dotslashbit I am almost done with this issue, but I'm encountering an error which I believe is causing the css style to break for the "multiselect-react-dropdown" library. I notice this issue was present before I started working on the project. I also want to mention that I'm still a newbie :D but i will try to solve it again today.
![Screenshot 2024-08-29 at 11 26 45 am (2)](https://github.com/user-attachments/assets/caa49d47-5cc1-47f1-89fe-2c85422164da)

- CSS style breaks like below picture
![Screenshot 2024-08-29 at 11 27 48 am (2)](https://github.com/user-attachments/assets/eff381d5-d1e2-49c5-977d-72f6a9e19aba)

I noticed that when I refresh the page after the popup _**'No issues found matching the current criteria. Try adjusting your filters'**_ appears, the CSS works as intended and the hydration error also disappears.
![Screenshot 2024-08-29 at 11 27 27 am (2)](https://github.com/user-attachments/assets/29cec54d-35d3-4be3-a6bf-24451e151f9a)

- CSS works as  intended
![Screenshot 2024-08-29 at 11 25 14 am (2)](https://github.com/user-attachments/assets/2459da88-6f2a-44f2-b9a2-9af7e8a83d6a)

- Hydration error disappear
![Screenshot 2024-08-29 at 11 25 33 am (2)](https://github.com/user-attachments/assets/2789412a-8efd-4c04-9800-1be8a220b938)

**Comment by dotslashbit** [comment] 2024-08-29 02:08
@ST-KO congrats making it work, there's nothing rush to finish working on it, take your time. @Sechorda can you help him on this?

**Comment by Sechorda** [comment] 2024-08-30 01:16
@dotslashbit Yes, I can help. I will have more time tomorrow to dedicate to the issues i'm on.

**Comment by ST-KO** [comment] 2024-08-30 01:27
> @dotslashbit Yes, I can help. I will have more time tomorrow to dedicate to the issues i'm on.
> 
> Edit: Just noticed the PR for this issue.
> 
> @ST-KO nice.

@Sechorda Thank you :D

**Closed** 2024-08-30 03:57 UTC
Labels: good first issue
